[Discord.App]
ApplicationID = "1519382220823986277"
PublicKey = "87ea754c944b0fe05c25319ba66433b8e7725e37055f2adf08dfea4f7f0a2bfd"

[Discord.App.Auth]
DevPass = "."
AuthToken = "."

[Discord.Command]
Prefix = ";"

[Bot.Command.getEnv]
AuthedUsers = [808381764623532102]

[Runtime.TypeChecking]
Typeguard = true
Beartype = true
