[project]
name = "carnivorebot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "discord-py>=2.7.1",
    "flask[async]>=3.1.3",
    "huggingface-hub>=1.27.0",
    "psutil>=7.2.2",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]

[tool.uv]
compile-bytecode = true
