from .admin import *
from .checkIsSpam import *
from .gdpr import *
from .getEnv import *
from .githubIssueMention import *
from .legal import *
from .pingPong import *
from .serverConfig import *
from .shellcmd import *
