.TH "CarnivoreBot Contributor Documentation" 1 0000-00-00 Subsystems Abstract

.SH PURPOSE
The abstract subsystem primarily consists of abstract classes used in the rest of the project.

Abstract classes are used for various purposes, such as:

.IP \(bu 4
Ensuring all methods are implemented, and no method was forgotten

.IP \(bu 4
Ensuring classes of the correct structure are being passed to an API

.SH CONTENTS
The abstract subsystem currently conists of:

.IP \(bu 4
feature.py (see \fIabstract(2)\fP)

.SH SEE ALSO
abstract(2)
