.TH "CarnivoreBot Contributor Documentation" 1 0000-00-00 Subsystems Core

.SH PURPOSE
The core subsystem contains functions, classes, and APIs that are at the core of the project.

.SH CONTENTS
The core subsystem is structured as follows:

.IP - 4
dc \- the code utilised for communication between the CarnivoreBot code and \fBdiscord.py\fR library (see \fIcore(2)\fR)

.IP - 4
feat \- the code handling registering features, and communication between feature threads and the main thread

.IP - 4
log \- the code handling logging and error handling

.IP - 4
runtime \- the code handling management and validation of runtime state

.IP - 4
starttime \- the code handling management of runtime state at the start of execution

.SH SEE ALSO
\fIfeat(1)\fR
\fIcore(2)\fR
