.TH "CarnivoreBot Contributor Documentation" 1 0000-00-00 Backend Subsystems

.SH STRUCTURE
The overall project is structured as follows:

.IP - 4
main.py

.IP - 4
subsystems

.IP - 8
core

.IP - 12
dc

.IP - 12
feat

.IP - 12
log

.IP - 12
runtime

.IP - 12
starttime

.IP - 8
feat

.IP - 8
utils

.IP - 12
cache

.IP - 12
obj

.IP - 12
visual

.IP - 8
tests

.IP - 12
integration

.IP - 12
unit

.IP - 12
utils

.SH SUBSYSTEMS
CarnivoreBot is separated into multiple subsystems. These are:

.IP \(bu 4
abstract \- contains abstract classes used in the rest of the project

.IP \(bu 4
core \- contains functions, classes, and APIs that are at the core of the project

.IP \(bu 4
feat \- contains features and commands

.IP \(bu 4
utils \- contains various, small utility functions

.IP \(bu 4
tests \- contains unit tests and integration tests for the project, via pytest

.SH SEE ALSO
\fIabstract(1)\fP
\fIfeat(1)\fP
